# Generated by Django 5.1.4 on 2026-08-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("name_uz", models.CharField(max_length=150, verbose_name="Nomi (UZ)")),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nomi (RU)"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        default="MYRON",
                        max_length=100,
                        verbose_name="Brend",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("women", "Ayollar / Women"),
                            ("men", "Erkaklar / Men"),
                            ("unisex", "Unisex / Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                        verbose_name="Toifa",
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        choices=[
                            ("parfum", "Extrait de Parfum"),
                            ("edp", "Eau de Parfum"),
                            ("edt", "Eau de Toilette"),
                            ("edc", "Eau de Cologne"),
                        ],
                        default="edp",
                        max_length=10,
                        verbose_name="Konsentratsiya",
                    ),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(default=50, verbose_name="Hajmi (ml)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Narxi ($)"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Eski narxi ($)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Asosiy rasm"
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Qo'shimcha rasm",
                    ),
                ),
                (
                    "short_description_uz",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="Qisqa tavsif (UZ)"
                    ),
                ),
                (
                    "short_description_ru",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="Qisqa tavsif (RU)"
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, verbose_name="To'liq tavsif (UZ)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="To'liq tavsif (RU)"),
                ),
                (
                    "composition_uz",
                    models.TextField(
                        blank=True,
                        help_text="Masalan: Bergamot, Yosemik yog'och, Amber, Musk",
                        verbose_name="Tarkibi / sastavi (UZ)",
                    ),
                ),
                (
                    "composition_ru",
                    models.TextField(blank=True, verbose_name="Tarkibi / sastavi (RU)"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sharhlar soni"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(default=False, verbose_name="Yangi mahsulot"),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="Ko'p sotilgan"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Faol (saytda ko'rinadi)"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Ombordagi soni"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Atir / Parfyum",
                "verbose_name_plural": "Atirlar / Parfyumlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Rasm"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qo'shimcha rasm",
                "verbose_name_plural": "Qo'shimcha rasmlar",
            },
        ),
    ]
