# Generated by Django 5.1.4 on 2026-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MYRON', max_length=100, verbose_name='Sayt nomi')),
                ('phone', models.CharField(default='+998 90 123 45 67', max_length=50, verbose_name='Telefon raqami')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/myron_perfume', verbose_name='Instagram havola')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/myron_perfume', verbose_name='Telegram havola')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Bosh sahifa rasmi (Hero)')),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Biz haqimizda 1-rasm')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Biz haqimizda 2-rasm')),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
