# Generated by Django 5.1.4 on 2026-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Atir / Parfyum', 'verbose_name_plural': 'Atirlar / Parfyумлар'},
        ),
        migrations.AlterField(
            model_name='product',
            name='composition_ru',
            field=models.TextField(blank=True, verbose_name='Состав (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Полное описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Ayollar / Женский'), ('men', 'Erkaklar / Мужской'), ('unisex', 'Unisex / Унисекс')], default='unisex', max_length=10, verbose_name='Toifa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=220, verbose_name='Краткое описание (RU)'),
        ),
    ]
