# Generated by Django 5.1.4 on 2026-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_alter_product_composition_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_user_rating',
            field=models.BooleanField(default=True, verbose_name="Foydalanuvchi reytingi blokini ko'rsatish"),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_when_to_wear',
            field=models.BooleanField(default=True, verbose_name="Qachon foydalanish blokini ko'rsatish"),
        ),
    ]
