# Generated by Django 5.1.4 on 2026-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_show_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes_ru',
            field=models.TextField(blank=True, verbose_name='Базовая нота (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_notes_uz',
            field=models.TextField(blank=True, help_text='Masalan: Vanil, amber, mushk. Vergul yoki yangi qatorda yozing.', verbose_name='Bazaviy nota (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes_ru',
            field=models.TextField(blank=True, verbose_name='Средняя нота (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes_uz',
            field=models.TextField(blank=True, help_text='Masalan: Atirgul, yasmin, dolchin. Vergul yoki yangi qatorda yozing.', verbose_name="O'rta nota (UZ)"),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes_ru',
            field=models.TextField(blank=True, verbose_name='Верхняя нота (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes_uz',
            field=models.TextField(blank=True, help_text='Masalan: Bergamot, limon, pushti murch. Vergul yoki yangi qatorda yozing.', verbose_name='Yuqori nota (UZ)'),
        ),
    ]
