# Generated by Django 5.1.4 on 2026-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_base_notes_ru_product_base_notes_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Atir / Parfyum', 'verbose_name_plural': 'Atirlar / Parfyumlar'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature1_icon',
            field=models.CharField(blank=True, default='🌿', max_length=20, verbose_name='1-xususiyat emojisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature1_text_ru',
            field=models.CharField(blank=True, default='Собрано из лучших уголков мира', max_length=255, verbose_name='1-xususiyat matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature1_text_uz',
            field=models.CharField(blank=True, default='Dunyoning eng sara joylaridan yetkazilgan', max_length=255, verbose_name='1-xususiyat matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature1_title_ru',
            field=models.CharField(blank=True, default='Качественный состав', max_length=150, verbose_name='1-xususiyat sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature1_title_uz',
            field=models.CharField(blank=True, default='SIFATLI TARKIB', max_length=150, verbose_name='1-xususiyat sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature2_icon',
            field=models.CharField(blank=True, default='🎓', max_length=20, verbose_name='2-xususiyat emojisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature2_text_ru',
            field=models.CharField(blank=True, default='Создано профессиональными парфюмерами', max_length=255, verbose_name='2-xususiyat matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature2_text_uz',
            field=models.CharField(blank=True, default='Professional parfyumerlar tomonidan yaratilgan', max_length=255, verbose_name='2-xususiyat matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature2_title_ru',
            field=models.CharField(blank=True, default='Опытные парфюмеры', max_length=150, verbose_name='2-xususiyat sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature2_title_uz',
            field=models.CharField(blank=True, default='MOHIR USTALAR', max_length=150, verbose_name='2-xususiyat sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature3_icon',
            field=models.CharField(blank=True, default='💎', max_length=20, verbose_name='3-xususiyat emojisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature3_text_ru',
            field=models.CharField(blank=True, default='Изысканная упаковка и детали', max_length=255, verbose_name='3-xususiyat matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature3_text_uz',
            field=models.CharField(blank=True, default='Nafis qadoqlash va nozik detallar', max_length=255, verbose_name='3-xususiyat matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature3_title_ru',
            field=models.CharField(blank=True, default='Роскошный опыт', max_length=150, verbose_name='3-xususiyat sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature3_title_uz',
            field=models.CharField(blank=True, default='HASHAMATLI TAJRIBA', max_length=150, verbose_name='3-xususiyat sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature4_icon',
            field=models.CharField(blank=True, default='🛡️', max_length=20, verbose_name='4-xususiyat emojisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature4_text_ru',
            field=models.CharField(blank=True, default='100% оригинальность и качество', max_length=255, verbose_name='4-xususiyat matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature4_text_uz',
            field=models.CharField(blank=True, default='100% originallik va sifat kafolati', max_length=255, verbose_name='4-xususiyat matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature4_title_ru',
            field=models.CharField(blank=True, default='Гарантия качества', max_length=150, verbose_name='4-xususiyat sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_feature4_title_uz',
            field=models.CharField(blank=True, default='KAFOLAT', max_length=150, verbose_name='4-xususiyat sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(blank=True, default='В MYRON мы верим, что духи — это не просто аромат, это заявление, эмоция и воспоминание. Наши ароматы создаются опытными парфюмерами из лучших мировых ингредиентов.', verbose_name='Biz haqimizda matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_uz',
            field=models.TextField(blank=True, default="MYRON'da biz atir shunchaki hid emas — u bir bayonot, bir hissiyot, bir xotira ekaniga ishonamiz. Bizning atirlarimiz dunyoning eng sara ingredientlaridan mohir parfyumerlar tomonidan tayyorlanadi, sizga tengsiz sifat va nafosat bag'ishlaydi.", verbose_name='Biz haqimizda matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_ru',
            field=models.CharField(blank=True, default='ИСКУССТВО ИЗЫСКАННЫХ АРОМАТОВ', max_length=200, verbose_name='Biz haqimizda sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_uz',
            field=models.CharField(blank=True, default="NOZIK ATIRLAR SAN'ATI", max_length=200, verbose_name='Biz haqimizda sarlavha (UZ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='concentration',
            field=models.CharField(choices=[('parfum', 'Parfyum ekstrakti'), ('edp', 'Parfyum suvi'), ('edt', 'Tualet suvi'), ('edc', 'Odekolon')], default='edp', max_length=10, verbose_name='Konsentratsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Ayollar'), ('men', 'Erkaklar'), ('unisex', 'Unisex')], default='unisex', max_length=10, verbose_name='Toifa'),
        ),
    ]
