# Generated by Django 5.1.4 on 2026-08-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_subtitle_ru',
            field=models.CharField(blank=True, default='В каждой капле отражается изысканный вкус, высокое качество и эмоции.', max_length=255, verbose_name='Biz haqimizda ostki matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_subtitle_uz',
            field=models.CharField(blank=True, default='Har bir tomchida nozik did, yuqori sifat va takrorlanmas hissiyot aks etadi.', max_length=255, verbose_name='Biz haqimizda ostki matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_buy_ru',
            field=models.CharField(blank=True, default='Купить сейчас', max_length=100, verbose_name='Sotib olish tugmasi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_buy_uz',
            field=models.CharField(blank=True, default='Xarid qilish', max_length=100, verbose_name='Sotib olish tugmasi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_details_ru',
            field=models.CharField(blank=True, default='Подробнее', max_length=100, verbose_name='Batafsil tugmasi (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_details_uz',
            field=models.CharField(blank=True, default="Batafsil ma'lumot", max_length=100, verbose_name='Batafsil tugmasi (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_subtitle_ru',
            field=models.CharField(blank=True, default='Выберите уникальный аромат и оформите быстрый заказ.', max_length=255, verbose_name='Katalog ostki matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_subtitle_uz',
            field=models.CharField(blank=True, default="O'zingizga mos unikal aromatlarni tanlang va buyurtma bering.", max_length=255, verbose_name='Katalog ostki matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title_ru',
            field=models.CharField(blank=True, default='ЭКСКЛЮЗИВНАЯ ПАРФЮМЕРИЯ', max_length=200, verbose_name='Katalog sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title_uz',
            field=models.CharField(blank=True, default='EKSKLYUZIV PARFYUMERIA', max_length=200, verbose_name='Katalog sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle_ru',
            field=models.CharField(blank=True, default='Есть вопросы? Позвоните нам или напишите в социальных сетях.', max_length=255, verbose_name='Kontaktlar ostki matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle_uz',
            field=models.CharField(blank=True, default="Savollaringiz bormi? Bizga qo'ng'iroq qiling yoki ijtimoiy tarmoqlarda yozing.", max_length=255, verbose_name='Kontaktlar ostki matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title_ru',
            field=models.CharField(blank=True, default='СВЯЖИТЕСЬ С НАМИ', max_length=200, verbose_name='Kontaktlar sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title_uz',
            field=models.CharField(blank=True, default="BIZ BILAN BOG'LANING", max_length=200, verbose_name='Kontaktlar sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.TextField(blank=True, default='MYRON Perfume — Символ высокого качества и изысканности. Все права защищены.', verbose_name='Footer matni (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_uz',
            field=models.TextField(blank=True, default='MYRON Perfume — Yuqori sifat va nafosat ramzi. Barcha huquqlar himoyalangan.', verbose_name='Footer matni (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_ru',
            field=models.CharField(blank=True, default='Смотреть каталог', max_length=100, verbose_name='Hero tugmasi matni (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn_uz',
            field=models.CharField(blank=True, default="Katalogni ko'rish", max_length=100, verbose_name='Hero tugmasi matni (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.TextField(blank=True, default='Коллекция утонченных ароматов, созданных из лучших французских ингредиентов.', verbose_name='Hero ostki matn (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_uz',
            field=models.TextField(blank=True, default='Eng sara va eksklyuziv fransuz ingredientlaridan tayyorlangan nafis atirlar kolleksiyasi.', verbose_name='Hero ostki matn (UZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='MYRON PERFUME — ДОМ ИЗЫСКАННОЙ ПАРФЮМЕРИИ', max_length=255, verbose_name='Hero sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_uz',
            field=models.CharField(blank=True, default='MYRON PERFUME — HASHAMATLI PARFYUMERLAR UYI', max_length=255, verbose_name='Hero sarlavha (UZ)'),
        ),
    ]
