# Generated by Django 5.1.4 on 2026-08-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('message', models.TextField(blank=True, verbose_name='Xabar / Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi / Новый'), ('confirmed', 'Tasdiqlangan / Подтверждён'), ('shipped', 'Yuborilgan / Отправлен'), ('done', 'Bajarilgan / Выполнен'), ('cancelled', 'Bekor qilingan / Отменён')], default='new', max_length=15, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami summa ($)')),
                ('telegram_notified', models.BooleanField(default=False, verbose_name='Telegramga yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Buyurtma tarkibi',
                'verbose_name_plural': 'Buyurtma tarkiblari',
            },
        ),
    ]
