# Generated by Django 5.1.4 on 2026-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('shipped', 'Yuborilgan'), ('done', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=15, verbose_name='Holati'),
        ),
    ]
